### ISSUE TITLE
Hiera data dir can not be set to a fact

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#157]
When setting hiera datadir setting to a fact: e.g. `datadir: "%{facts.hiera_data_dir}"`

The webinterface does not show any data.

As this is a valid setting we must ensure that we are also able to use a fact as datadir setting within HDM.

**Comment by oneiros** [comment]
I have been studying the docs here: https://www.puppet.com/docs/puppet/7/hiera_config_yaml_5.html#hiera_config_yaml_5 and am still not 100% sure where variable interpolation is allowed in `hiera.yaml` and where it is not.

AFAICT only the per-hierarchy `datadir` and the options to specify the location of files (`path`/`paths`/`globs` etc.) support variable interpolation. On the other hand the default `datadir` option does **not** support it.

Can you confirm that I am reading this correctly?

@rwaffen You mentioned there might be other options that support variable interpolation. Am I missing something?

**Comment by rwaffen** [comment]
i thought, but cannot find it, that one may use interpolation in each key.
our customer with the problem has a hiera.yaml like this:

```yaml
---
version: 5
hierarchy:
  - name: "Puppet Hierarchy"
    lookup_key: puppet_function_lookup_key     # customer related special backend
    datadir: "%{facts.customer.hieradata_path}"
    globs:
...
```
