### ISSUE TITLE
HDM does not initialize database

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#275]
When running a Manual Installation (https://github.com/betadots/hdm/blob/main/MANUAL_INSTALL.md) the task to set up the database fails:

```
bundle exec rails db:setup
/opt/hdm/vendor/bundle/ruby/3.2.0/gems/io-event-1.3.3/lib/io/event/support.rb:24: warning: IO::Buffer is experimental and both the Ruby and C interface may change in the future!
bin/rails aborted!
NoMethodError: undefined method `[]' for nil:NilClass (NoMethodError)

      if Rails.configuration.hdm['read_only']
                                ^^^^^^^^^^^^^
/opt/hdm/config/routes.rb:32:in `block (3 levels) in <top (required)>'
```

HDM config:
```
cat config/hdm.yml
---
production:
  read_only: true
  allow_encryption: false
  puppet_db:
    server: http://localhost:8080
  hiera_config_file: "hiera.yaml"
  config_dir: /etc/puppetlabs/code
```
