### ISSUE TITLE
Custom function mapping not working

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#293]
According to documentation one should set a mapping between the individual function and the used data backend:

1. Hiera.yaml
```yaml
---
version: 5
defaults:
  datadir: "%{facts.external_facts.datadir}"
  lookup_key: custom_eyaml_function
  #data_hash: yaml_data
hierarchy:
  - name: "Per-node data (yaml version)"
    path: "nodes/%{::trusted.certname}.yaml"
  - name: "Other YAML hierarchy levels"
    paths:
      - "common.yaml"
```

2. HDM.yml
```yaml
---
development:
  read_only: false
  allow_encryption: true
  puppet_db:
    server: "http://localhost:8080"
  config_dir: '/etc/puppetlabs/code'
  custom_lookup_function_mapping:
    custom_eyaml_function: eyaml
```

3. Result from HDM:
```
HDM Error
unknown backend custom_eyaml_function
```

Content of backends variable:
```
{"data_hash"=>{"json_data"=>:json, "yaml_data"=>:yaml}, "lookup_key"=>{"eyaml_lookup_key"=>:eyaml, :custom_eyaml_function=>:eyaml}}
```
