### ISSUE TITLE
globs do not show data on v2.0.0

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#329]
Hiera.yaml:
```
---
version: 5
defaults:
  lookup_key: puppet_function_lookup_key
  datadir: "%{facts.external_facts.datadir}"
  #data_hash: yaml_data
  # Comment
hierarchy:
  - name: "Per-node data (yaml version)"
    globs:
      - "nodes/%{trusted.certname}.yaml"
      - "common.yaml"
```
