### ISSUE TITLE
On Puppet Enterprise: unknown backend classifier_data 

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#489]
We need to whitelist (and don't do anything) if a hiera.yaml has the PE classifier data entry:

```yaml
---
# Hiera 5 Global configuration file

version: 5

# defaults:
#   data_hash: yaml_data
# hierarchy:
#  - name: Common
#    data_hash: yaml_data
hierarchy: 
 - name: Classifier Configuration Data
   data_hash: classifier_data
```
