### ISSUE TITLE
Check possibility for hdm to run locally without authentication

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#54]
We are considering the idea to let HDM run in a container without authentication for local (dev workstation) usage.

General question:

is it possible to easily disable authentication?

**Comment by rwaffen** [comment]
- should be a flag in hdm config file
- hide elements which show user / logged in as
- or add demo/dummy user to automatically use in this mode
- in production mode dummy user should be deactivaed

**Comment by oneiros** [comment]
I quickly prototyped the idea of using a dummy user for this here: ff9b009d310430cc6bc7a9dfdb68dfd7d070bffe

As you can see, the diff is quite small.

If you would like to pursue this further, I would maybe add a test or two and open a PR.

**Comment by tuxmea** [comment]
@oneiros We have at least two requests from Puppet community on Slack who asked for disabling authentication.
It would be nice to have a config switch to deactivate and maybe switch the user authentication (local vs LDAP).

**Comment by tuxmea** [comment]
Disabling authentication is no longer working.
This is the HDM config file:

```
---
development:
  read_only: false
  allow_encryption: true
  puppet_db:
    server: "https://puppetdb:8081"
  config_dir: '/etc/puppetlabs/code'
  authentication_disabled: true
```
